apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ingress.yaml
  - helpdesk-web.yaml
  - internal-api.yaml
  - postgres.yaml
  - configmap-init-sql.yaml
